extends:
  - eslint:recommended
  - plugin:node/recommended
plugins:
  - node
  - mocha
rules:
  comma-dangle: 0
  node/no-unsupported-features:
    - error
    - version: 6
  no-console: 0
  semi:
    - 2
    - always
